### ISSUE TITLE
v5.20 progress

### ISSUE THREAD

**Issue by gileli121** [WindowTop/WindowTop-App#287]
# Planned features

1. #133
2. #63
3. #283

# Bonus planned feature (may not be included yet)
1. Always-on-Top - Add crop feature - the ability to cut specific region from a window and show only that region
2. #183

# Update:

Features https://github.com/WindowTop/WindowTop-App/issues/63 and https://github.com/WindowTop/WindowTop-App/issues/283 ware delayed to v5.21
I already started with #283, but the whole thing took a little longer than I expected because I am busy with other stuff in life, and  #133 seems big enough to justify a new version. It also tested for about two weeks or more, and no issues were found, and there are more reasons for doing it... So better to release it now instead of taking the risk of releasing an unstable version.

v5.20 will be released soon today with only #133 included

**Comment by sebastienbo** [comment]
Yoohoo 1: Cool, a crop feature, can't wait to test that out (so many applications possible)
And yoohoo 2: we can reset per window configuration with one single button

I did notice something odd with the new version 5.19.3 , the minimize integration doesn't work on Microsoft teams windows, although the green arrow does work. And the minimize integration still works for the other windows.
However this might have to do something with the way microsoft teams displays windows, because it is a really strange program how it starts, I don't think it's a normal window (Teams I mean).

**Comment by gileli121** [comment]
Thanks for your reply

About the issue that you mentioned, it is a known issue, and it can't be fixed because some windows are too custom, and in these cases, there is no generic way that I could come up with how to detect if the custom button is used as a minimize button.

The integration with the minimize button should work with most windows.
It can even detect the minimize button in a few more extreme cases of customized windows, but my method is still not 100% perfect and can't work for windows that don't give any clue about the button's purpose.

**Comment by camAtGitHub** [comment]
When is the 5.20 beta being released? :-P 😋

**Comment by gileli121** [comment]
@camAtGitHub 
It may take between 1-3 weeks (depending on how frequently I work on it) to implement 
[Shrink/PiP] Shrink - Live Preview - Add Crop feature #133

And the development has already started.

**Comment by gileli121** [comment]
@sebastienbo 
About the problem with the Anchors feature is that sometimes it may distract you (due to a lot of icons jumping around),
I think that I have an idea - 

From my experience, this is most common when you scroll with the mouse.
I think hiding the anchors each time you scroll and maybe disabling the auto-move while scrolling - is a nice solution and very easy to implement.

What do you think?

**Comment by sebastienbo** [comment]
Hi,

I think that will indeed be better.

2 possibilities:
a) Disabling the jumping of the anchors until the scrolling is done (1
second grace period, in case of scrolling further)
b) hide anchors until scrolling done (1 sec graceperiod) this has the
advantage of being able to see the content while scrolling until scrolling
ends .

2 possible triggers:
scrolling (this is what we currently talk about)
moving windows (same distracting effect, during the movement of a window it
is distracting that they jump arround, espcecially when you want to drag
something to it (like files))

**Comment by gileli121** [comment]
@sebastienbo 
Thanks for the suggestion.

What option would you use? Option A or option B?

Option A - `Disabling the jumping of the anchors until the scrolling is done`
Option B - `hide anchors until scrolling done`

I will probably provide both options, but I still need to know the default.

**Comment by sebastienbo** [comment]
Gil,

That is a though question.

Both have advantages and disadvantages, i Primarly thought about the
advantages, but have no idea if one of them might be unpleasant for some
reason.
Intuitively I think Option A has the least impact since you still see the
anchors.
However Option B could benefit from a "view" perspective, it makes anchors
less disruptive for the user content,
and that was exactly what you tried to achieve with the functionality "stay
away from text and images", during scrolling this offcourse created the
jumping effect.
So option B would be more in line with what you tried to achieve with the
"stay away from text and images" feature.

I would try option B, but if it feels also disruptive by user feedback, go
back to option A

**Comment by gileli121** [comment]
@sebastienbo 

Thank you for the feedback.
I also have some opinions here, but I don't want to share them because I want your opinion to come only from you.

After I finish implementing https://github.com/WindowTop/WindowTop-App/issues/133, I will implement this suggestion, provide both options, and ask you to test and share with me what option you prefer.

**Comment by sebastienbo** [comment]
Haha , thank you

But don't worry, I'm a critical thinker even for my own opinions,
especially when i hear the pros and cons from others .

I'm used to software architecture and user experience subjects.

From my experience the best ideas come from thinking together, and even
then, some unexpected use cases may rise of you going use the application
in every day life.

**Comment by gileli121** [comment]
@sebastienbo 
I think that the first option (only to disable the auto-move) is the best.
The fact that icons are hidden for a few seconds and then shown again, then hidden and shown again (and so on during scrolling) is possibly another form of distraction

**Comment by gileli121** [comment]
@camAtGitHub @sebastienbo 

Here is the first beta version with the implementation of https://github.com/WindowTop/WindowTop-App/issues/133
[WindowTop 5.20.0-beta1 - setup.exe.zip](https://github.com/WindowTop/WindowTop-App/files/11131304/WindowTop.5.20.0-beta1.-.setup.exe.zip)

Here is a demo video:

https://user-images.githubusercontent.com/17680514/229336467-943e22bd-2e49-4e5f-a9ae-81595576606e.mp4


Note that I have not yet added the icon for the crop button.
It is hard to figure out what icon to choose.
See here to see the options:
https://github.com/WindowTop/WindowTop-App/issues/133#issuecomment-1492909905


Other than that, most/all stuff is already implemented and tested as much as I can. 
It should also handle different DPI scaling.

Let me know please how it works.

**Comment by camAtGitHub** [comment]
Thanks Ill try it out. 
Also I have attached some icons for your consideration.
https://www.flaticon.com/free-icon/resize_3819534
https://www.flaticon.com/free-icon/resize_4804543
https://www.flaticon.com/free-icon/resize_9853636
https://www.flaticon.com/free-icon/reduce_1891254
https://www.flaticon.com/free-icon/resize_4402015
https://www.flaticon.com/free-icon/resize_1545281
https://www.flaticon.com/free-icon/resize_3819534
https://www.flaticon.com/free-icon/resize_1391597
https://www.flaticon.com/free-icon/resizing_6577310
https://www.flaticon.com/free-icon/resize_6791345
https://www.flaticon.com/free-icon/resize-option_4115565
https://www.flaticon.com/free-icon/resize-option_4763967
https://www.flaticon.com/free-icon/resize_7746052
https://www.flaticon.com/free-icon/crop_1830657
https://www.flaticon.com/free-icon/expand_722400
https://www.flaticon.com/free-icon/maximize_4085254

**Comment by gileli121** [comment]
@camAtGitHub @sebastienbo 
I released a new beta version.

https://user-images.githubusercontent.com/17680514/234123893-2a6be022-397e-42da-81f1-bea5d3890031.mp4

This time the core functionality is fully implemented, including many bug fixes and stability improvements.
I also added an icon.

Please check it out here:
https://github.com/WindowTop/WindowTop-App/issues/133#issuecomment-1520875451

Thank you.

**Comment by gileli121** [comment]
@camAtGitHub @sebastienbo 
I am considering if to replace one of the tasks in v5.20 (that are #63 and #283) with #295  

Let me know what you think.
thanks

**Comment by gileli121** [comment]
Features https://github.com/WindowTop/WindowTop-App/issues/63 and https://github.com/WindowTop/WindowTop-App/issues/283 ware delayed to v5.21
I already started with #283, but the whole thing took a little longer than I expected because I am busy with other stuff in life, and  #133 seems big enough to justify a new version. It also tested for about two weeks or more, and no issues were found, and there are more reasons for doing it... So better to release it now instead of taking the risk of releasing an unstable version.

v5.20 will be released soon today

**Comment by gileli121** [comment]
Closed.
Opened for v5.21 #298
