### ISSUE TITLE
Product key for new computer

### ISSUE THREAD

**Issue by tajmahal226** [WindowTop/WindowTop-App#294]
Hi there - hope you are doing well. Love the product, thanks for making it. 

I had a quick question: I purchased a product key for my old computer - but just recently got a new one. Was wondering if there was a way to transfer that product key to my new computer? 

Thank you,
Tyler

**Comment by gileli121** [comment]
@tajmahal226 
Just use the key. If the key were used on more than three computers, the app would ask you if you want to deactivate it on the other computers after you enter the product key. Click yes to do it, and then you should be fine
