### ISSUE TITLE
Always On Top AOT (red) border line does not adjust size with window when resizing horizontally or vertically

### ISSUE THREAD

**Issue by adambisho** [WindowTop/WindowTop-App#302]
When setting Always On Top (AOT) with hotkey Alt-z, I get a red-line around my VLC media player window.  When I adjust the size with the mouse by dragging the the border horizontally or vertically, the red-line does not adjust.  The red line will adjust if dragging by the corner of the window.  I am using Windows 10, and a registered version WindowTop 5.20.0.  Thanks for an awesome program.  Love love love this!.  

I didn't see this already listed in the issues.  Forgive me if I missed it.  See pictures below.

![Screenshot - 6_17_2023 , 10_59_43 AM](https://github.com/WindowTop/WindowTop-App/assets/68546145/e3d6ed06-77f6-4b44-aad3-cb30e9f55672)
![Screenshot - 6_17_2023 , 10_58_27 AM](https://github.com/WindowTop/WindowTop-App/assets/68546145/20ed3f74-a5a3-4b98-911f-9e55b7fb29ba)
![Screenshot - 6_17_2023 , 10_58_16 AM](https://github.com/WindowTop/WindowTop-App/assets/68546145/4c4782bf-4b9f-4d5f-9e93-47db3767e109)
![Screenshot - 6_17_2023 , 10_57_45 AM](https://github.com/WindowTop/WindowTop-App/assets/68546145/fc8f7266-c271-4ead-889c-bba5b4087a4b)

**Comment by gileli121** [comment]
@adambisho 
Wow
I can't belive that I missed it.. 
This bug must be fixed as hotfix ASAP.
I am working on it now

Thanks for the report

**Comment by gileli121** [comment]
Seems that I already found it during the development of v5.20
But somehow I forgot to include the fix in the branch of 5.20

I will release soon a new version with the hotfix.

**Comment by adambisho** [comment]
Thanks!  Glad I served as a reminder.  Love the software.  This makes my life so much easier.  I may buy more licenses.

**Comment by gileli121** [comment]
@adambisho 
Thank you!
I fixed it and released it in v5.20.2
You can download it from here:
https://github.com/WindowTop/WindowTop-App/releases/tag/v5.20.2

If you use the MS Store version, you will need to wait up to 3 days because it takes some time until Microsoft verify the new release.

**Comment by adambisho** [comment]
@gileli121 
I've downloaded and installed it.  Thanks again for this program and all the work you do on it!

**Comment by gileli121** [comment]
I am glad to do the work
It released now to Microsoft Store
Closing this as resolved.
