### ISSUE TITLE
v5.22 progress - Update: Released!

### ISSUE THREAD

**Issue by gileli121** [WindowTop/WindowTop-App#304]
In the end, #287 was ended up with only the crop feature, other features delayed to v5.22

# Planned features
1. [PiP (Picture-in-Picture) - Implement a two-click method to enable it quickly like how it has done in Linux Elementary-OS](https://github.com/WindowTop/WindowTop-App/issues/313)

# Bonus planned feature (may not be included yet)

1. #63
3. #283
4. #183

# Update

Feature  #313 was fully implemented and released in the final version 5.22
Here is the result of this huge effort :)

https://www.youtube.com/watch?v=tUwFFwrCO24

Version 5.22 is available to download from here
https://github.com/WindowTop/WindowTop-App/releases/tag/v5.22.0

This is no longer beta.
It is after a lot of testing

Let me know how it works :)

**Comment by RONJOS7777** [comment]
Your application is fabulous, please could you add spanish language...
Thank you so much...

**Comment by gileli121** [comment]
@RONJOS7777, thanks for your feedback.
If you can translate to Spanish, please contact via contact@windowtop.info 
And I will provide you with a localization file with instructions to translate.

**Comment by gileli121** [comment]
About plans for the 5.22 release, I decided to implement [PiP (Picture-in-Picture) - Implement a two-click method to enable it quickly like how it has done in Linux Elementary-OS](https://github.com/WindowTop/WindowTop-App/issues/313) in 5.22 ASAP.
Because it turns out that three months after the crop developed in WindowTop, the Microsoft PowerToys community started to develop the crop feature.

I suspect that they copy again.
Their last attempt failed to attract users.. they cannot make a better product. They are allowed to use only public Windows API, so they have no advantage in development.

But I am glad that they try to catch up with the level of quality of WindowTop. 
But they are stupid. instead of purchasing, I suspect (can't prove it) that they copy like losers.

**Comment by Mystqr4** [comment]
I could careless what Microsoft does. They are always half assing things anyway and wouldn't even bother to maintain it. Your version is always going to be better because you are so focused and invested into this application.
Big companies are always the worst.
I guess just keep going and pushing new features and refining everything.

**Comment by gileli121** [comment]
Thanks. 

> I guess just keep going and pushing new features and refining everything.

Yes but only features for improving the efficiency of multi-tasking with multiple windows.

Pushing every possible new feature, like what they try to do, is not what I and the users want. This is what they are doing.
They create something like a bomb with tons of stuff. Some are related to particular use cases, and some are related to the area of this app.
It is like installing many very different programs you may not need in one app.
WindowTop goal is only to feature for multi-tasking with a lot of windows (the dark-mode feature is a small exception, but everything else can help in multitasking in its own way)
Doing app that focuses on everything seems wrong.. and I am not surprised that PowerToys take more than 500MB for its installation and temporary files, and dependencies) while WindowTop takes only 34 and has a portable version.

**Comment by Mystqr4** [comment]
> Thanks.
> 
> > I guess just keep going and pushing new features and refining everything.
> 
> Yes but only features for improving the efficiency of multi-tasking with multiple windows.
> 
> Pushing every possible new feature, like what they try to do, is not what I and the users want. This is what they are doing. They create something like a bomb with tons of stuff. Some are related to particular use cases, and some are related to the area of this app. It is like installing many very different programs you may not need in one app. WindowTop goal is only to feature for multi-tasking with a lot of windows (the dark-mode feature is a small exception, but everything else can help in multitasking in its own way) Doing app that focuses on everything seems wrong.. and I am not surprised that PowerToys take more than 500MB for its installation and temporary files, and dependencies) while WindowTop takes only 34 and has a portable version.

Nor do I. I meant it in a way to compliment the thought that all that you implement is well considered and implemented in such a way that actually works. Microsoft half asses everything. Look at their tabbed explorer... terrible!
I only meant small little features that compliment the overall application itself in a similar way to what you had planned for version 5.22

Yep, its become so bloated over the years. 

I have every faith in what you are doing. It's always going to be the better choice. I am also glad people are continuing to buy it and support you.

**Comment by gileli121** [comment]
Good news -
Beta 10 passed all initial testing and seems stable.
I can make a final release, but I prefer to go on bug reports that reported using #151 
And I am also waiting for translation updates.

**Comment by gileli121** [comment]
@Mystqr4 @RONJOS7777 

# Update

Feature  #313 was fully implemented and released in the final version 5.22
Here is the result of this huge effort :)

https://www.youtube.com/watch?v=tUwFFwrCO24


Version 5.22 is available to download from here
https://github.com/WindowTop/WindowTop-App/releases/tag/v5.22.0

This is no longer beta.
It is after a lot of testing

Let me know how it works :)
