### ISSUE TITLE
Default PIP Size (Picture-in-Picture) doesn't change default PIP size

### ISSUE THREAD

**Issue by adambisho** [WindowTop/WindowTop-App#310]
When I use the PIP, I get one-size, and it's a bit small for me.  I see an option of "Default PIP size" but that doesn't seem to change anything. I know I can manually change the PIP, but I have to do that each time I restart the program every time I close and reopen an application.
 Is this a bug, or am I missing something?  I didn't see any request on this issue.

Windows 10
Window Top version 5.21

**Comment by gileli121** [comment]
@adambisho 
I checked it, and I reproduced the bug!
I am surprised that it broke!

This is indeed a bug.
The default PIP size should be set to the default size when first enabling it...
I checked when it first broke, and I was surprised even more.. the last time that these settings worked as expected was in v5.19.4 (two major versions before the current one!)

For now, you can try 5.19.4 from here:
https://github.com/WindowTop/WindowTop-App/releases/tag/v5.19.4


I will work on bugfix this weekend.

Thank you for the report

**Comment by gileli121** [comment]
@adambisho 
Fixed and released in https://github.com/WindowTop/WindowTop-App/releases/tag/v5.21.1

**Comment by adambisho** [comment]
Thanks!  I should have said something earlier, but I thought it might just be something I was doing wrong.  Love this program!
________________________________

**Comment by gileli121** [comment]
Glad to help and for giving useful program and help a lot of people in their daily work :)
I am closing this issue.
If you still get it somehow, please reopen it.
Thank you
