### ISSUE TITLE
Deactivate Notification

### ISSUE THREAD

**Issue by username011111** [WindowTop/WindowTop-App#311]
How can i deactivate that blue windows popping up on the right corner?

idk if thats the right place to ask questions like that, sorry.

**Comment by gileli121** [comment]
Hi, do you mean to notification when you toggle the feature like always on top?
Go to settings:
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/e1e82d7f-5a6e-4fbc-a05a-49d80736f79a)
In the new window, click on the star icon 
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/fa142fed-6305-46aa-a3d6-7e205714588e)

Under the "Set Top feature"
make sure that this option is off:
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/ac5fa4b1-7f75-46c7-b70b-d540155fa4f7)

You also have it under the "Opacity feature":
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/a9ed3c73-3c61-4190-a7c6-20bc95831246)

Make sure that it is off also there. 

Once you do it, you will not see notifications when you toggle always-on-top or opacity via hotkeys.
