### ISSUE TITLE
Toolbar problem on Notepad++ with Dspellcheck pluggin

### ISSUE THREAD

**Issue by Mystqr4** [WindowTop/WindowTop-App#326]
Just like when I hover over the the little hover drop down menu in QTtabbar it triggers the Windowtop toolbar and creates an issue when trying to use said feature this is once again a problem in Notepad++ using the DSpellcheck pluggin's drop down menu for the correct spelling and makes it difficult to reach the spelling correction.
I have provided an example pic although my pointer is missing which at time of screenshot would be hovering over the red arrow box.

 I don't believe this was a problem in regards to Notepad++ up until recently in the new version 5.22 although the QTtabbar one has been around for a while.
![notepad++_jzH5VLYBO1](https://github.com/WindowTop/WindowTop-App/assets/65718578/3d8ff3b4-1ecd-4e07-a4ae-f04bc911a5bc)

**Comment by gileli121** [comment]
@Mystqr4 
Thanks for the report.
This is a regression from bugfix 
https://github.com/WindowTop/WindowTop-App/issues/320

I know how to fix it again without causing regressions like this.
I will do it soon.

**Comment by gileli121** [comment]
@Mystqr4 
Fixed.
Please check the beta version here:

https://github.com/WindowTop/WindowTop-App/releases/tag/v5.22.1-beta

It also includes a few more minor bugfixes that I found since the last stable.

Let me know please how it works.

**Comment by Mystqr4** [comment]
The bug in Notepad++ seems to be fixed now.

**Comment by gileli121** [comment]
Great.
Closed.
https://github.com/WindowTop/WindowTop-App/releases/tag/v5.22.2
Includes additional fixes that you may need.

> Fixed regression from 5.22.1 that the settings UI freezes after the computer wakes up from sleep. The regression was caused by the fix Fixed slow performance issue in the settings window

If will soon push an update notification during the upcoming days (if everything is alright for sure)
