### ISSUE TITLE
PIP with chrome never remembers any settings.

### ISSUE THREAD

**Issue by dreamfeel** [WindowTop/WindowTop-App#327]
Despite having interact mode turned off in options and trying to save PIP never remembers. It always puts it into interact mode, read mode and smart drag. I'd love to have both of these turned off by default as it's a pain to have to unselect them every time (especially with having to wait for the sub menus to appear*)

Does the PIP save button work with chrome? It works per domain I think (which I like) but only within the same instance. eg, if I close chrome and reopen it doesn't remember. 

* Perhaps there could also be an option to have the menu completely open inc these sub menus (inc save and delete save)
Almost every time I want to PIP I want to crop, this feature is amazing. It is kind of annoying to have to hover for this to appear. 

Incredible tool though! If I could these little fiddly things fixed it could totally revolutionise how i use a computer.

**Comment by gileli121** [comment]
Hello, to disable interact and read-mode by default, follow these steps:

1. Open all settings:
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/793c77e3-5a37-42a3-ae63-b906a424ab9a)

In the "PiP & Crop" tab, make sure that this option is disabled
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/78569b89-6a1b-4d1a-a4e9-f38f62de5ce6)

After that, restart WindowTop for the changes to take place.


About the save button, it is per application. If you save the configuration, it will save it for all windows of the same application.

**Comment by gileli121** [comment]
Fixed for user.
Closed.
