### ISSUE TITLE
Default opacity level is not work

### ISSUE THREAD

**Issue by lionwu** [WindowTop/WindowTop-App#328]
Hello, the Default opacity level is not work. I've set it to 15%, but it still changes to 75% when I open the program. Please fix it, thanks!
![123](https://github.com/WindowTop/WindowTop-App/assets/13290191/50375976-b997-485a-a4e9-ab632dfa7899)

**Comment by gileli121** [comment]
@lionwu 
Sorry for the late reply.
I checked it.
It works, but only for new windows or when you close a window and reopen it again.

For example, if you change the opacity to 20% while Window A is open, the slider on Window A will still be 75%.
But if you open a new window - Window B, for example, then the slider will be at 20%.

**Comment by lionwu** [comment]
It's work by using "Save window configuration" button, thank you very much! 
![image](https://github.com/WindowTop/WindowTop-App/assets/13290191/9b4adc94-1e12-4d7c-aa2c-22ae6c7e6272)

**Comment by gileli121** [comment]
Great
Enjoy :)
