### ISSUE TITLE
[Feature Request] Settings for dark mode to not filter images by default

### ISSUE THREAD

**Issue by vanbang9710** [WindowTop/WindowTop-App#330]
Currently filter images option can only be toggled per window ![|50pct](https://i.imgur.com/rToDfma.png)

**Comment by gileli121** [comment]
Hello, the option is available under the advanced features settings.
Go to 

![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/a9544aba-c722-47d1-8fad-419577934279)

Make sure that this option is enabled
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/0831db7f-8140-4e7f-8436-2eb599e66dd7)

You will notice the change after you open a new window and try again or restart WindowTop.
If you don't see the change yet, check if you saved a specific configuration on the window by clicking on the arrow button:
![image](https://github.com/WindowTop/WindowTop-App/assets/17680514/f6044045-8d73-4784-9726-a82368b105e4)

If you see X button in addition to the save button, click on the X button to delete the configuration for this window.
After that, try again. It should enable it by default.
