### ISSUE TITLE
Develop feature to allow users to link between activation key and Google/Microsoft account

### ISSUE THREAD

**Issue by gileli121** [WindowTop/WindowTop-App#332]
Recently, it seems that this capability is very needed for various reasons.

Once it is developed, anyone with an activation key can sign in with Google or Microsoft to link the key to their Google or Microsoft account.

This way, instead of counting computers, it will count users.

About the Microsoft Store version: there is an activation method based on the Microsoft Store in case a user purchases via their store.
We don't have such an issue with the MS Store activation method (because the concept is to purchase using the MS Store account). 
I will develop this capability to activation-key method.

**Comment by Mystqr4** [comment]
As long as this is an option then that is okay. I prefer not to link up anything with Google, Microsoft or even Facebook, (even though Facebook is thankfully not an option here)

I guess I will have to see how this pans out.

**Comment by gileli121** [comment]
@Mystqr4 
It will be an option.
Without this it will count by computer (instead of email)

**Comment by gileli121** [comment]
The development of it is probably finished.
The testing part is very, very complicated....

I will send a screenshot of the feature later.
Anyway, the option to use the license key as done now (without a link to the account) will always be available. This is not meant to be used by small users anyway.

**Comment by gileli121** [comment]
@Mystqr4 
It implemented
https://github.com/WindowTop/WindowTop-App/releases/tag/v5.23.0

Some license keys (not what I am selling now) will require a link to your email. It is not mandatory or needed for existing license keys or plans that are currently sold.

[Link license to email.webm](https://github.com/user-attachments/assets/c2e4797d-366e-4fe5-ab0c-923aed66188e)

[Activate by email (login or verification link).webm](https://github.com/user-attachments/assets/1335be85-5d04-4f49-a1eb-d895ca385763)

**Comment by gileli121** [comment]
I enabled this feature for regular license keys also.
But it applies only to new license keys.

**Comment by gileli121** [comment]
Implemented and released.
Note that, unlike the first video, it will not force you to link to an email.
It was an example with a license that does force it. But I turned off this flag and didn't sell such licenses.
