### ISSUE TITLE
Issue with Nvidia Graphics Card

### ISSUE THREAD

**Issue by Mohsyn** [WindowTop/WindowTop-App#341]
When I enable Nvidia Card in settings, and later run some game, it will not allow the screen to be resized and force focus to return to windows from the game screen until either WT is stopped or Card is reset by changing to Intel and back to Nvidia.

**Comment by gileli121** [comment]
Hello, can you record a small video that shows this problem?
You can use https://www.screentogif.com/  to do quick recording.
And save it as a `webm` or `mp4` file. It is small enough to send it here.

It will help me understand the issue so I can try to fix it when I get to it.
Thank you.

**Comment by gileli121** [comment]
Closed due to inactivity
