### ISSUE TITLE
Request: Option to export settings and reset to default settings

### ISSUE THREAD

**Issue by WZ-Tong** [WindowTop/WindowTop-App#63]
Export settings
Reset to default (Hotkeys)

Maybe upload it to Microsoft Store so that we can update it automatically? (Like taskbarX)

**Comment by gileli121** [comment]
Thanks for the suggestion.
I will probably implement the first suggestion

About second suggestion, I thought about it.
Maybe I will do it also.

**Comment by gileli121** [comment]
@WZ-Tong 
For now you can export settings from here:
%appdata%/windowtop

You will see there `settings.json` file.

**Comment by WZ-Tong** [comment]
Thanks, but now it can't set hotkeys back to default (Just a small problem and it doesn't matter)

**Comment by gileli121** [comment]
I reopened it because your request to set default settings seems good idea and it was not done yet.
I will do it but first I want stable version before I adding more functionality

**Comment by gileli121** [comment]
@WZ-Tong  
I've started working on it as part of #389. Here's the first screenshot:  
![image](https://github.com/user-attachments/assets/eebcc98c-8581-4bd2-8d63-0ab74450490e)  

How does it look?

**Comment by gileli121** [comment]
Implemented in [v5.24](https://github.com/WindowTop/WindowTop-App/releases/tag/5.24)

Currently beta version
![image](https://github.com/user-attachments/assets/0b19c86c-2bd2-40ad-bba9-43b282e1c435)
![image](https://github.com/user-attachments/assets/8ffaf2ed-bc62-4052-90b5-6fde198baece)

**Comment by WZ-Tong** [comment]
Sorry to be late, this is GREAT~！

**Comment by gileli121** [comment]
@WZ-Tong 

I implemented additional improvements in version 5.24.1.

One of them is adding the import feature to the wizard page:

[windowtop load settings from wizard.webm](https://github.com/user-attachments/assets/cd674cd2-2d57-40fe-9ccf-a1984ac8013e)

Release notes:

* Added spinner icon while import is in progress
* Added a confirmation message notifying the user that the import will override current settings and the app will restart, and requesting user confirmation to continue
* Added a notification message shown after the app restarts to confirm import completion
* Fixed an issue where auto-start with Windows was not applied from imported settings
* The first page of the window assistant shows the import option, and the last page shows the export button

Please check it out.
Download the pre-release from here:
https://github.com/WindowTop/WindowTop-App/releases/tag/5.24

Thanks!
